framework:
    messenger:
        transports:
            default: 'enqueue://default?topic[name]=%env(ENQUEUE_QUEUE)%&queue[name]=%env(ENQUEUE_QUEUE)%&receiveTimeout=3'

        routing:
        # Route your messages to the transports
        # 'App\Message\YourMessage': async
