twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        i18n: '@qpost\Service\TranslationService'
        gitlab: '@qpost\Service\GitLabService'
