image: alpine:latest

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - deploy

cache:
    paths:
    - ~/.ssh/
    - vendor/

deploy:
    stage: deploy
    script:
    - apk update
    - 'which rsync || apk add rsync'
    - 'which ssh-agent || apk add openssh-client'
    - 'which git || apk add git'
    - 'which php7 || apk add php7'
    - 'which php7-fileinfo || apk add php7-fileinfo'
    - 'which php7-curl || apk add php7-curl'
    - 'which php7-ctype || apk add php7-ctype'
    - 'which php7-gmp || apk add php7-gmp'
    - 'which php7-gd || apk add php7-gd'
    - 'which php7-mbstring || apk add php7-mbstring'
    - 'which composer || apk add composer'
    - 'which npm || apk add npm'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - git submodule update --depth 50
    - composer install --no-dev
    - composer dump-autoload -o
    - npm i
    - npm run build
    - rsync -avze ssh --exclude=.git --exclude=.env.local --exclude=var ./ ssh-gigadrivegroup@zeryther.lima-ssh.de:~/html/qpost/
    - rsync -avze ssh --exclude=.git --exclude=.env.local --exclude=var ./ root@node1.qpo.st:~/web/qpost/
    - ssh -t ssh-gigadrivegroup@zeryther.lima-ssh.de 'cd ~/html/qpost/ && /opt/lima-php/7.2/bin/php ~/phpbin/composer.phar install --no-dev && /opt/lima-php/7.2/bin/php ~/phpbin/composer.phar dump-autoload -o && /opt/lima-php/7.2/bin/php bin/console doctrine:migrations:migrate --no-interaction'
    - ssh -t root@node1.qpo.st 'cd ~/web/qpost/ && composer install --no-dev && composer dump-autoload -o && sudo chmod -R 777 ./* && php bin/console doctrine:migrations:migrate --no-interaction'
    only:
    - master
