sentry:
    dsn: '%env(SENTRY_SDN)%'
    register_error_listener: false
    monolog:
        error_handler:
            enabled: true
            level: error
    options:
        environment: '%kernel.environment%'
        release: '%env(VERSION)%'
        excluded_exceptions:
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            - Doctrine\DBAL\Exception\DriverException
            - Doctrine\DBAL\Exception\ConnectionException
            - Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException